//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightCube.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battery
    {
        public int BatteriesID { get; set; }
        public int Voltage { get; set; }
        public string Information { get; set; }
    }
}
