//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightCube.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class elementsDBEntities : DbContext
    {
        public elementsDBEntities()
            : base("name=elementsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Battery> Batteries { get; set; }
        public virtual DbSet<LED> LEDs { get; set; }
        public virtual DbSet<Resistor> Resistors { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
